In [2]:
data = open('hindu_JK.txt',encoding='utf-8',errors='ignore')

In [3]:
data1 = data.read()

In [4]:
article_text  = data1.split('.')

In [5]:
len(article_text)

45

In [6]:
import re
article_text_new = []

In [7]:
for i in range(0,len(article_text)):
    article_text_new.append(re.sub('\n', ' ',article_text[i]))

In [8]:
article_text_new.pop()

''

In [9]:
article_text_new

['The August 5 decision has led to a state wherein the very basis of a potential step of conflict resolution has been undone',
 ' While the long-standing ideological commitment of the Bharatiya Janata Party to undo Article 370 of the Indian Constitution is why Jammu and Kashmir (J&K) was stripped of its special status as well as Statehood making it a simmering cauldron of discontent, our collective mythmaking about Kashmir is the deeper reason for what the former State has become today',
 ' Kashmir has been a favourite site of our national mythmaking; myths that have over the years assumed larger-than-life manifestations in our collective psyche',
 ' Kashmir has most things that popular myths are made of: mesmerising beauty, cross-border terror, deep states and their agents, war and heroism',
 ' Clearly, myths about Kashmir are not created by the right wing alone but by successive Indian governments over several decades, enthusiastically embellished by a vibrant, popular culture',
 ' D

In [10]:
formatted_article_text = []
for i in range(0,(len(article_text_new)-1)):
    formatted_article_text.append(re.sub('[^a-zA-Z]', ' ', article_text_new[i] ))
    formatted_article_text[i] = re.sub(r'\s+', ' ', formatted_article_text[i])


In [11]:
len(article_text_new)

44

In [12]:
import numpy as np
import pandas as pd
import nltk
nltk.download('punkt') # one time execution

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [13]:
from nltk.tokenize import sent_tokenize
sentences = []
for s in article_text_new:
  sentences.append(sent_tokenize(s))

sentences = [y for x in sentences for y in x] # flatten list

In [14]:
sentences

['The August 5 decision has led to a state wherein the very basis of a potential step of conflict resolution has been undone',
 ' While the long-standing ideological commitment of the Bharatiya Janata Party to undo Article 370 of the Indian Constitution is why Jammu and Kashmir (J&K) was stripped of its special status as well as Statehood making it a simmering cauldron of discontent, our collective mythmaking about Kashmir is the deeper reason for what the former State has become today',
 ' Kashmir has been a favourite site of our national mythmaking; myths that have over the years assumed larger-than-life manifestations in our collective psyche',
 ' Kashmir has most things that popular myths are made of: mesmerising beauty, cross-border terror, deep states and their agents, war and heroism',
 ' Clearly, myths about Kashmir are not created by the right wing alone but by successive Indian governments over several decades, enthusiastically embellished by a vibrant, popular culture',
 ' D

In [15]:
# remove punctuations, numbers and special characters
clean_sentences = pd.Series(sentences).str.replace("[^a-zA-Z]", " ")

# make alphabets lowercase
clean_sentences = [s.lower() for s in clean_sentences]

In [16]:
clean_sentences

['the august   decision has led to a state wherein the very basis of a potential step of conflict resolution has been undone',
 ' while the long standing ideological commitment of the bharatiya janata party to undo article     of the indian constitution is why jammu and kashmir  j k  was stripped of its special status as well as statehood making it a simmering cauldron of discontent  our collective mythmaking about kashmir is the deeper reason for what the former state has become today',
 ' kashmir has been a favourite site of our national mythmaking  myths that have over the years assumed larger than life manifestations in our collective psyche',
 ' kashmir has most things that popular myths are made of  mesmerising beauty  cross border terror  deep states and their agents  war and heroism',
 ' clearly  myths about kashmir are not created by the right wing alone but by successive indian governments over several decades  enthusiastically embellished by a vibrant  popular culture',
 ' d

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [18]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [19]:
# function to remove stopwords
def remove_stopwords(sen):
    sen_new = " ".join([i for i in sen if i not in stop_words])
    return sen_new

In [20]:
clean_sentences = [remove_stopwords(r.split()) for r in clean_sentences]

In [21]:
# Extract word vectors
word_embeddings = {}
f = open('glove.6B.100d.txt', encoding='utf-8')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    word_embeddings[word] = coefs
f.close()

In [88]:
len(word_embeddings.get('got'))

100

In [75]:
sentence_vectors = []
for i in clean_sentences:
  if len(i) != 0:
    v = sum([word_embeddings.get(w, np.zeros((100,))) for w in i.split()])/(len(i.split())+0.001)
  else:
    v = np.zeros((100,))
  sentence_vectors.append(v)

In [76]:
k = i.split()
k[0]
[word_embeddings.get(k[0], np.zeros((100,)))]

[array([-4.3959e-02,  1.8936e-01,  6.6110e-01, -4.9007e-01,  3.2211e-01,
        -3.4161e-01, -6.8480e-02,  3.1364e-01, -7.1142e-01,  5.7436e-01,
        -3.3588e-01, -5.2279e-01, -3.9075e-01, -8.9694e-02,  4.6371e-01,
        -3.5610e-01,  8.4576e-01, -2.6188e-02, -1.9328e-01, -8.3846e-02,
         3.1806e-01, -1.9812e-01,  3.0009e-01,  6.9189e-02,  5.4470e-01,
        -5.9193e-01,  5.4221e-01, -6.2876e-01, -5.3447e-01,  4.2334e-01,
         3.0869e-02,  9.7164e-01, -5.6222e-01,  4.5752e-02, -5.7100e-01,
         8.0185e-02, -8.1434e-02, -6.0260e-01,  1.6466e-01, -4.0281e-01,
        -4.7701e-01, -5.1950e-01,  1.2777e-01, -4.3775e-01,  2.6602e-01,
         4.8752e-01, -6.0220e-02, -5.2622e-01,  3.7687e-01, -1.8007e-01,
         3.0166e-02, -9.4577e-02,  1.6330e-01,  5.9041e-01, -4.8877e-01,
        -3.4230e+00,  1.3113e-01, -8.0386e-02,  1.8978e+00,  1.8857e-01,
        -5.7300e-01,  8.6358e-01,  2.1116e-03,  3.6060e-01,  8.0475e-01,
        -1.3954e-01, -5.3935e-02,  3.8873e-01,  3.0

In [80]:
i.split()

['new',
 'delhi',
 'kashmir',
 'policy',
 'today',
 'caught',
 'rock',
 'hard',
 'place',
 'indication',
 'path',
 'chose',
 'august',
 'would',
 'lead',
 'peace',
 'development',
 'valley',
 'revert',
 'pre',
 'august',
 'status',
 'quo',
 'would',
 'political',
 'suicide',
 'bjp']

In [78]:
len(i)

175

In [82]:
len(v)

100

In [83]:
v

array([-1.45019084e-01, -1.13780014e-01,  2.22362906e-01, -1.52855590e-02,
        8.64610970e-02, -1.38966829e-01, -7.09188581e-02,  3.51853222e-02,
       -5.73081672e-02,  1.96821898e-01, -1.13291748e-01,  9.53568891e-02,
        3.65162522e-01,  4.14495058e-02,  1.28590807e-01, -2.21195474e-01,
        1.38623163e-01, -8.71854872e-02, -4.40937668e-01,  6.06502108e-02,
        3.70232016e-01, -1.83312654e-01,  2.16119513e-01,  5.68334050e-02,
       -1.34105414e-01, -5.63448705e-02, -9.69892591e-02, -3.36435676e-01,
        1.01826385e-01, -1.65538535e-01, -7.15319738e-02,  3.79352540e-01,
        3.05628683e-02,  4.23815623e-02, -1.21044405e-02,  1.45331735e-03,
        1.16594747e-01,  8.10212642e-02, -8.44877213e-02, -1.54915795e-01,
       -5.97050369e-01, -4.97210957e-02,  3.71604681e-01, -2.86684573e-01,
        8.54078904e-02, -3.03134859e-01,  2.75341511e-01, -7.67751113e-02,
       -8.74300599e-02, -5.02892137e-01,  7.46021420e-02, -1.37283936e-01,
        1.49632886e-01,  

In [73]:
sentence_vectors

[array([ 9.61572155e-02, -4.16671149e-02,  3.23357671e-01,  1.98623046e-01,
         1.34998905e-02, -9.55907628e-02, -2.30379123e-02, -5.00139035e-02,
         8.71012360e-03, -6.34501502e-02, -1.35184065e-01, -1.24123067e-01,
         2.14156568e-01, -9.99893695e-02,  1.26519457e-01, -9.07711908e-02,
        -1.04849912e-01,  1.22117348e-01, -4.51566190e-01, -8.49430934e-02,
         1.63089693e-01, -2.85194963e-01,  2.45923370e-01,  1.33703753e-01,
         5.22765182e-02, -8.36342126e-02, -3.06749437e-02, -9.05868560e-02,
         5.46753965e-02, -9.39563662e-02, -1.76998451e-02,  1.09400511e-01,
        -1.05537936e-01, -1.81974262e-01, -1.91189975e-01, -4.10242751e-02,
         1.37715667e-01, -1.32514134e-01, -2.79390872e-01, -1.31963909e-01,
        -4.52994794e-01,  2.13453267e-02,  2.82980978e-01, -2.32685387e-01,
        -1.20360114e-01, -2.64249414e-01,  1.73333317e-01, -2.06315219e-01,
        -3.77117813e-01, -5.22855222e-01,  1.48621857e-01, -2.29945734e-01,
         9.4

In [49]:
len(word_embeddings.get('goat'))

100

In [36]:
np.zeros((100,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
sentence_vectors[1].reshape(100,1)

array([[-0.27095076],
       [ 0.12680593],
       [ 0.25225535],
       [ 0.04397307],
       [ 0.05292389],
       [ 0.13389194],
       [-0.2937226 ],
       [-0.09636166],
       [-0.05356793],
       [ 0.24841888],
       [-0.18598549],
       [-0.02961777],
       [ 0.3934156 ],
       [ 0.05408224],
       [-0.16715829],
       [-0.19015828],
       [ 0.14996792],
       [ 0.05978186],
       [-0.2692977 ],
       [-0.16268766],
       [ 0.31528533],
       [ 0.00971488],
       [ 0.25304395],
       [ 0.01747975],
       [-0.03666985],
       [-0.02221026],
       [-0.04550838],
       [-0.16203377],
       [ 0.10673279],
       [-0.21807964],
       [ 0.14676884],
       [ 0.40574485],
       [ 0.04658745],
       [-0.08216824],
       [-0.1415622 ],
       [-0.01817633],
       [ 0.26959112],
       [ 0.133165  ],
       [-0.16784723],
       [-0.01110397],
       [-0.4118616 ],
       [ 0.02097186],
       [ 0.48393276],
       [-0.29920936],
       [ 0.00968811],
       [-0

In [61]:
# similarity matrix
sim_mat = np.zeros([len(sentences), len(sentences)])

In [62]:
from sklearn.metrics.pairwise import cosine_similarity

In [72]:
sim_mat[3][1]

0.8414880633354187

In [64]:
for i in range(len(sentences)):
  for j in range(len(sentences)):
    if i != j:
      sim_mat[i][j] = cosine_similarity(sentence_vectors[i].reshape(1,100), sentence_vectors[j].reshape(1,100))[0,0]

In [52]:
import networkx as nx

nx_graph = nx.from_numpy_array(sim_mat)
scores = nx.pagerank(nx_graph)

In [53]:
ranked_sentences = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)

In [54]:
# Extract top 10 sentences as the summary
for i in range(10):
  print(ranked_sentences[i][1])

 That “Kashmir needs to be reunited with the rest of India” has been a powerful claim made by such representations and political articulations: no matter Kashmir was easily India’s most securitised State with various central institutions and agencies undermining not only what was left of Article 370 prior to August last year but also impeding the elected government’s power in the former State
 J&K, as a matter of fact, has been doing much better than most other Indian States and one of the reasons for this was the land reforms carried out in the State in the early 1950s which was possible precisely because of the presence of Article 370
’ Notwithstanding the fact that a cash-strapped country such as ours has inherent limitations on how much development assistance it can provide to J&K over other States, the reality may well be that development may not lead to pacification of the conflict in Kashmir
 Home Minister Amit Shah’s statements last year on the floor of Parliament that Article 

In [55]:
ranked_sentences

[(0.023182747030762767,
  ' That “Kashmir needs to be reunited with the rest of India” has been a powerful claim made by such representations and political articulations: no matter Kashmir was easily India’s most securitised State with various central institutions and agencies undermining not only what was left of Article 370 prior to August last year but also impeding the elected government’s power in the former State'),
 (0.023132214704854562,
  ' J&K, as a matter of fact, has been doing much better than most other Indian States and one of the reasons for this was the land reforms carried out in the State in the early 1950s which was possible precisely because of the presence of Article 370'),
 (0.023126445773094983,
  '’ Notwithstanding the fact that a cash-strapped country such as ours has inherent limitations on how much development assistance it can provide to J&K over other States, the reality may well be that development may not lead to pacification of the conflict in Kashmir')

In [1]:
word_embeddings

NameError: name 'word_embeddings' is not defined

In [89]:
m = [0.418 0.24968 -0.41242 0.1217 0.34527 -0.044457 -0.49688 -0.17862 -0.00066023 -0.6566 0.27843 -0.14767 -0.55677 0.14658 -0.0095095 0.011658 0.10204 -0.12792 -0.8443 -0.12181 -0.016801 -0.33279 -0.1552 -0.23131 -0.19181 -1.8823 -0.76746 0.099051 -0.42125 -0.19526 4.0071 -0.18594 -0.52287 -0.31681 0.00059213 0.0074449 0.17778 -0.15897 0.012041 -0.054223 -0.29871 -0.15749 -0.34758 -0.045637 -0.44251 0.18785 0.0027849 -0.18411 -0.11514 -0.78581
, 0.013441 0.23682 -0.16899 0.40951 0.63812 0.47709 -0.42852 -0.55641 -0.364 -0.23938 0.13001 -0.063734 -0.39575 -0.48162 0.23291 0.090201 -0.13324 0.078639 -0.41634 -0.15428 0.10068 0.48891 0.31226 -0.1252 -0.037512 -1.5179 0.12612 -0.02442 -0.042961 -0.28351 3.5416 -0.11956 -0.014533 -0.1499 0.21864 -0.33412 -0.13872 0.31806 0.70358 0.44858 -0.080262 0.63003 0.32111 -0.46765 0.22786 0.36034 -0.37818 -0.56657 0.044691 0.30392
. 0.15164 0.30177 -0.16763 0.17684 0.31719 0.33973 -0.43478 -0.31086 -0.44999 -0.29486 0.16608 0.11963 -0.41328 -0.42353 0.59868 0.28825 -0.11547 -0.041848 -0.67989 -0.25063 0.18472 0.086876 0.46582 0.015035 0.043474 -1.4671 -0.30384 -0.023441 0.30589 -0.21785 3.746 0.0042284 -0.18436 -0.46209 0.098329 -0.11907 0.23919 0.1161 0.41705 0.056763 -6.3681e-05 0.068987 0.087939 -0.10285 -0.13931 0.22314 -0.080803 -0.35652 0.016413 0.10216
]

SyntaxError: invalid syntax (<ipython-input-89-b3692ab7f36c>, line 1)